import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import SidebarButton from "@/components/SidebarButton"
import Sidebar from "@/components/Sidebar"
import MainContent from "@/components/MainContent"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "New Service",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-white`}
      >
        <Sidebar />
        <MainContent>{children}</MainContent>
      </body>
    </html>
  )
}
